/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.sun.tools.javac.util.ArrayUtils;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.ListModel;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionListener;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author martingermain
 */
public class Home extends javax.swing.JFrame {
    
    private final javax.swing.JFileChooser openFileChooser;
    private DefaultListModel listTourModel;
    private JList jListTour;
    private javax.swing.JOptionPane jOptionPaneInfo, jOptionPaneWarning, jOptionPaneError;
    
    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        openFileChooser = new JFileChooser();
        openFileChooser.setCurrentDirectory(new File("C:\\"));
        openFileChooser.setFileFilter(new FileNameExtensionFilter("XML File", "xml"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHeader = new javax.swing.JPanel();
        JLabelAppName = new javax.swing.JLabel();
        jPanelMap = new javax.swing.JPanel();
        jPanelManager = new javax.swing.JPanel();
        jButtonAddTour = new javax.swing.JButton();
        jLabelTittleTour = new javax.swing.JLabel();
        jButtonDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelHeader.setBackground(new java.awt.Color(0, 0, 51));
        jPanelHeader.setPreferredSize(new java.awt.Dimension(1000, 50));

        JLabelAppName.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        JLabelAppName.setForeground(new java.awt.Color(255, 255, 255));
        JLabelAppName.setText("Deli'velo");

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(JLabelAppName)
                .addContainerGap(881, Short.MAX_VALUE))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(JLabelAppName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelMap.setBackground(new java.awt.Color(153, 153, 153));
        jPanelMap.setPreferredSize(new java.awt.Dimension(600, 550));

        javax.swing.GroupLayout jPanelMapLayout = new javax.swing.GroupLayout(jPanelMap);
        jPanelMap.setLayout(jPanelMapLayout);
        jPanelMapLayout.setHorizontalGroup(
            jPanelMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanelMapLayout.setVerticalGroup(
            jPanelMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelMap, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        jPanelManager.setBackground(new java.awt.Color(51, 51, 51));
        jPanelManager.setPreferredSize(new java.awt.Dimension(400, 550));
        jPanelManager.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAddTour.setText("Add Tour");
        jButtonAddTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddTourActionPerformed(evt);
            }
        });
        jPanelManager.add(jButtonAddTour, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jLabelTittleTour.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabelTittleTour.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTittleTour.setText("Planned Tour :");
        jPanelManager.add(jLabelTittleTour, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        jPanelManager.add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, -1, -1));

        getContentPane().add(jPanelManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddTourActionPerformed
        int returnValue = openFileChooser.showOpenDialog(this);

        if( returnValue == JFileChooser.APPROVE_OPTION) {
            //try {
                listTourModel = new DefaultListModel();
                listTourModel.addElement("Jasmine Mehra");
                listTourModel.addElement("Ankit Mishra");
                listTourModel.addElement("Madhuri Sanghvi");
                listTourModel.addElement("Alok Kumar");
                listTourModel.addElement("Rohit Bothra");
                listTourModel.addElement("Rahul Aggarwal");


                //Create the list and put it in a scroll pane.
                jListTour = new JList(listTourModel);
                jListTour.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                jListTour.setSelectedIndex(0);
                //jListTour.addListSelectionListener(this);
                jListTour.setVisibleRowCount(5);
                JScrollPane jScrollPaneTour = new JScrollPane(jListTour);
                jScrollPaneTour.setBackground(new java.awt.Color(51, 51, 51));
                jScrollPaneTour.setForeground(new java.awt.Color(255, 255, 255));
                jScrollPaneTour.setBorder(null);
                jScrollPaneTour.setPreferredSize(new java.awt.Dimension(300, 95));
                // Code of sub-components and layout - not shown here
                
                jPanelManager.add(jScrollPaneTour, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 360, 330));
                jPanelManager.validate();
            //} catch(IOException ioe) {
                //jOptionPaneError = new JOptionPane();
                //jOptionPaneError.showMessageDialog(null, "Error Loading File", "Error", JOptionPane.ERROR_MESSAGE);
            //}
        }else {
            jOptionPaneWarning = new JOptionPane();
            jOptionPaneWarning.showMessageDialog(null, "No File Selected", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAddTourActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
         listTourModel.remove(jListTour.getSelectedIndex());
         jListTour.validate();
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelAppName;
    private javax.swing.JButton jButtonAddTour;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JLabel jLabelTittleTour;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelManager;
    private javax.swing.JPanel jPanelMap;
    // End of variables declaration//GEN-END:variables
}
